package policygen

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"
)

// renderModel carries everything the writers need beyond the raw specs: which
// matcher functions exist, what the fact frame holds, and which standard
// library packages the generated file therefore imports.
type renderModel struct {
	plan         policyPlan
	matchers     []renderedMatcher
	denyMatch    map[int]string
	routeMatch   map[string]string
	needsStrconv bool
	needsMath    bool
}

func (m renderModel) hasMatchers() bool { return len(m.matchers) > 0 }

// renderedMatcher is one generated predicate function.
type renderedMatcher struct {
	name    string
	comment string
	body    string
}

func renderPolicySource(options Options, importRoot string, policy loadedPolicy, vocab loadedVocabulary, plan policyPlan) (string, error) {
	meta := metadataFor(policy, vocab)
	model, err := buildRenderModel(policy.spec, plan)
	if err != nil {
		return "", err
	}
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by cervorules-policygen; DO NOT EDIT.")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "package %s\n\n", options.PackageName)
	fmt.Fprintln(&b, "import (")
	fmt.Fprintln(&b, `"context"`)
	fmt.Fprintln(&b, `"fmt"`)
	if model.needsMath {
		fmt.Fprintln(&b, `"math"`)
	}
	if model.needsStrconv {
		fmt.Fprintln(&b, `"strconv"`)
	}
	fmt.Fprintln(&b, `"strings"`)
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "cervorules %q\n", importRoot+"/core")
	fmt.Fprintf(&b, "cervoruntime %q\n", importRoot+"/runtime")
	fmt.Fprintf(&b, "%s %q\n", options.VocabularyPackage, options.VocabularyImport)
	fmt.Fprintln(&b, ")")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "type PolicyFactory struct{}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "func NewPolicyFactory() PolicyFactory { return PolicyFactory{} }")
	fmt.Fprintln(&b)
	writeMetadata(&b, meta)
	writeDefaultConfig(&b, policy.spec)
	writeValidateConfig(&b, options.VocabularyPackage, policy.spec)
	writeBuild(&b, policy.spec, model)
	writeFactFrame(&b, model)
	writeMatchers(&b, model)
	writeEngine(&b, model)
	return b.String(), nil
}

// conditionLiteral renders a rule's required condition names as Go source.
func conditionLiteral(requires []string) string {
	if len(requires) == 0 {
		return "nil"
	}
	var b strings.Builder
	b.WriteString("[]cervorules.Condition{")
	for i, name := range requires {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "cervorules.Condition(%q)", normalize(name))
	}
	b.WriteString("}")
	return b.String()
}

func writeMetadata(b *bytes.Buffer, meta PolicyMetadata) {
	fmt.Fprintln(b, "func (PolicyFactory) Metadata() cervoruntime.PolicyMetadata {")
	fmt.Fprintln(b, "return cervoruntime.PolicyMetadata{")
	fmt.Fprintf(b, "Name: %q,\n", meta.Name)
	fmt.Fprintf(b, "DSLVersion: %q,\n", meta.DSLVersion)
	fmt.Fprintf(b, "GeneratedWith: %q,\n", meta.GeneratedWith)
	fmt.Fprintf(b, "VocabularyHash: %q,\n", meta.VocabularyHash)
	fmt.Fprintf(b, "PolicyHash: %q,\n", meta.PolicyHash)
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
}

func writeDefaultConfig(b *bytes.Buffer, policy policySpec) {
	fmt.Fprintln(b, "func (PolicyFactory) DefaultConfig() cervoruntime.PolicyRuntimeConfig {")
	fmt.Fprintln(b, "return cervoruntime.PolicyRuntimeConfig{")
	if len(policy.TrustedUsers) > 0 {
		fmt.Fprintln(b, "TrustedUsers: []string{")
		for _, user := range policy.TrustedUsers {
			fmt.Fprintf(b, "%q,\n", user)
		}
		fmt.Fprintln(b, "},")
	}
	if policy.Defaults.Executor != "" {
		fmt.Fprintf(b, "DefaultExecutor: cervorules.Executor(%q),\n", normalize(policy.Defaults.Executor))
	}
	fmt.Fprintln(b, "OperationTargets: map[cervorules.Operation]cervorules.Target{")
	for _, route := range sortedRoutes(policy.Routes) {
		if route.DisabledByDefault {
			continue
		}
		fmt.Fprintf(b, "cervorules.Operation(%q): cervorules.Target(%q),\n", normalize(route.Operation), normalize(route.Target))
	}
	fmt.Fprintln(b, "},")
	fmt.Fprintln(b, "ExecutorFallbacks: map[cervorules.Executor][]cervorules.Executor{")
	// Fallbacks are keyed by executor, not by route, so two routes naming the
	// same executor describe one entry. Emitting one per route produced a Go
	// map literal with a duplicate constant key, which only failed in the
	// consumer's build. validate has already rejected conflicting lists, so
	// the first is the whole story.
	emittedFallbacks := map[string]struct{}{}
	for _, route := range sortedRoutes(policy.Routes) {
		if len(route.FallbackExecutors) == 0 {
			continue
		}
		executor := normalize(route.Executor)
		if _, ok := emittedFallbacks[executor]; ok {
			continue
		}
		emittedFallbacks[executor] = struct{}{}
		fmt.Fprintf(b, "cervorules.Executor(%q): {", executor)
		for _, fallback := range route.FallbackExecutors {
			fmt.Fprintf(b, "cervorules.Executor(%q),", normalize(fallback))
		}
		fmt.Fprintln(b, "},")
	}
	fmt.Fprintln(b, "},")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
}

func writeValidateConfig(b *bytes.Buffer, vocabPackage string, policy policySpec) {
	fmt.Fprintln(b, "func (PolicyFactory) ValidateConfig(cfg cervoruntime.PolicyRuntimeConfig) error {")
	fmt.Fprintf(b, "vocab := %s.Vocabulary()\n", vocabPackage)
	fmt.Fprintln(b, "var errs cervorules.Errors")
	if names := sortedConditionNames(policy); len(names) > 0 {
		// A policy that declares guards but is built without an evaluator would
		// silently allow everything those guards were meant to stop.
		fmt.Fprintln(b, "if cfg.Conditions == nil {")
		fmt.Fprintln(b, "errs = append(errs, cervorules.Error{")
		fmt.Fprintln(b, "Code: cervorules.ErrorCodeMissingConditions,")
		fmt.Fprintln(b, "Severity: cervorules.SeverityFatal,")
		fmt.Fprintln(b, "Component: \"policy\",")
		fmt.Fprintln(b, "Field: \"conditions\",")
		fmt.Fprintf(b, "Reason: %q,\n", "policy declares "+strconv.Itoa(len(names))+" condition(s) but no evaluator is configured")
		fmt.Fprintf(b, "Suggestion: %q,\n", "set PolicyRuntimeConfig.Conditions before building this policy")
		fmt.Fprintln(b, "})")
		fmt.Fprintln(b, "}")
	}
	fmt.Fprintln(b, "if cfg.DefaultExecutor != \"\" {")
	fmt.Fprintln(b, "errs = appendRuntimeValidationError(errs, vocab.ValidateExecutor(cfg.DefaultExecutor), \"defaults.executor\")")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "for operation, target := range cfg.OperationTargets {")
	writeLine(b, `operationField := fmt.Sprintf("operation_targets[%s]", operation)`)
	fmt.Fprintln(b, "errs = appendRuntimeValidationError(errs, vocab.ValidateOperation(operation), operationField)")
	fmt.Fprintln(b, "errs = appendRuntimeValidationError(errs, vocab.ValidateTarget(target), operationField+\".target\")")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "for executor, fallbacks := range cfg.ExecutorFallbacks {")
	writeLine(b, `executorField := fmt.Sprintf("executor_fallbacks[%s]", executor)`)
	fmt.Fprintln(b, "errs = appendRuntimeValidationError(errs, vocab.ValidateExecutor(executor), executorField)")
	fmt.Fprintln(b, "for i, fallback := range fallbacks {")
	writeLine(b, `errs = appendRuntimeValidationError(errs, vocab.ValidateExecutor(fallback), fmt.Sprintf("%s[%d]", executorField, i))`)
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "if len(errs) > 0 { return errs.SortStable() }")
	fmt.Fprintln(b, "return nil")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "func appendRuntimeValidationError(errs cervorules.Errors, err error, field string) cervorules.Errors {")
	fmt.Fprintln(b, "if err == nil { return errs }")
	fmt.Fprintln(b, "switch typed := err.(type) {")
	fmt.Fprintln(b, "case cervorules.Error:")
	fmt.Fprintln(b, "typed.Field = field")
	fmt.Fprintln(b, "return append(errs, typed)")
	fmt.Fprintln(b, "case cervorules.Errors:")
	fmt.Fprintln(b, "for _, item := range typed { item.Field = field; errs = append(errs, item) }")
	fmt.Fprintln(b, "return errs")
	fmt.Fprintln(b, "default:")
	fmt.Fprintln(b, "return append(errs, cervorules.Error{Code: cervorules.ErrorCodeInvalidRuntimeConfig, Field: field, Reason: err.Error()})")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
}

func writeBuild(b *bytes.Buffer, policy policySpec, model renderModel) {
	fmt.Fprintln(b, "func (PolicyFactory) Build(ctx context.Context, cfg cervoruntime.PolicyRuntimeConfig) (cervorules.Engine, error) {")
	fmt.Fprintln(b, "select {")
	fmt.Fprintln(b, "case <-ctx.Done():")
	fmt.Fprintln(b, "return nil, ctx.Err()")
	fmt.Fprintln(b, "default:")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "factory := PolicyFactory{}")
	fmt.Fprintln(b, "base := factory.DefaultConfig()")
	fmt.Fprintln(b, "cfg = mergeRuntimeConfig(base, cfg)")
	fmt.Fprintln(b, "if err := factory.ValidateConfig(cfg); err != nil { return nil, cervoruntime.NewPolicyBuildError(factory.Metadata(), err) }")
	fmt.Fprintln(b, "routes := map[cervorules.Operation]generatedRoute{")
	for _, route := range sortedRoutes(policy.Routes) {
		if route.DisabledByDefault {
			continue
		}
		writeRouteEntry(b, policy, route, "route matched", model)
	}
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "disabledRoutes := map[cervorules.Operation]generatedRoute{")
	for _, route := range sortedRoutes(policy.Routes) {
		if !route.DisabledByDefault {
			continue
		}
		writeRouteEntry(b, policy, route, "runtime override", model)
	}
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "trustedUsers := map[string]struct{}{}")
	fmt.Fprintln(b, "for _, user := range cfg.TrustedUsers {")
	fmt.Fprintln(b, "if normalized := strings.ToLower(strings.TrimSpace(user)); normalized != \"\" { trustedUsers[normalized] = struct{}{} }")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "for operation, target := range cfg.OperationTargets {")
	fmt.Fprintln(b, "route, ok := routes[operation]")
	fmt.Fprintln(b, "if !ok { route = disabledRoutes[operation] }")
	fmt.Fprintln(b, "route.target = target")
	fmt.Fprintln(b, "if route.executor == \"\" { route.executor = cfg.DefaultExecutor }")
	fmt.Fprintln(b, "if route.id == \"\" { route.id = string(operation) }")
	fmt.Fprintln(b, "if route.reason == \"\" { route.reason = \"runtime override\" }")
	fmt.Fprintln(b, "routes[operation] = route")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "disabledDenies := map[cervorules.Operation]string{")
	for _, route := range policy.Routes {
		if !route.DisabledByDefault {
			continue
		}
		reason := strings.TrimSpace(route.DisabledReason)
		if reason == "" {
			reason = "route disabled by default"
		}
		fmt.Fprintf(b, "cervorules.Operation(%q): %q,\n", normalize(route.Operation), reason)
	}
	fmt.Fprintln(b, "}")
	// Denies are an ordered slice, not a map: rules are evaluated in the order
	// they were authored and the first match wins. A map keyed by operation
	// allowed only one deny per operation, and emitted Go that did not compile
	// when a policy declared two.
	fmt.Fprintln(b, "denies := []generatedDeny{")
	for i, deny := range policy.Denies {
		writeDenyEntry(b, i, deny, model)
	}
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "return generatedEngine{routes: routes, denies: denies, disabledDenies: disabledDenies, trustedUsers: trustedUsers, defaultExecutor: cfg.DefaultExecutor, executorFallbacks: cfg.ExecutorFallbacks, conditions: cfg.Conditions}, nil")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	writeMergeConfig(b)
}

func writeRouteEntry(b *bytes.Buffer, policy policySpec, route routeSpec, fallbackReason string, model renderModel) {
	reason := route.ID
	if strings.TrimSpace(reason) == "" {
		reason = fallbackReason
	}
	// A route id is optional, but a trace step still has to name something a
	// reader can find in the policy file. `reason` falls back to the literal
	// "route matched", which names nothing, so the operation stands in instead.
	id := strings.TrimSpace(route.ID)
	if id == "" {
		id = normalize(route.Operation)
	}
	fmt.Fprintf(b, "cervorules.Operation(%q): {target: cervorules.Target(%q), executor: cervorules.Executor(%q), id: %q, reason: %q, requiresTrustedUser: %t, requires: %s",
		normalize(route.Operation), normalize(route.Target), generatedRouteExecutor(policy, route), id, reason, route.RequiresTrustedUser, conditionLiteral(route.Requires))
	if model.hasMatchers() {
		fmt.Fprintf(b, ", match: %s", matcherReference(model.routeMatch[normalize(route.Operation)]))
	}
	fmt.Fprintln(b, "},")
}

func writeDenyEntry(b *bytes.Buffer, index int, deny denySpec, model renderModel) {
	// An absent reason would put an empty string in the audit record. The id is
	// the one thing a deny always has.
	reason := deny.Reason
	if strings.TrimSpace(reason) == "" {
		reason = deny.ID
	}
	fmt.Fprint(b, "{")
	if operation := normalize(deny.Operation); operation != "" {
		fmt.Fprintf(b, "operation: cervorules.Operation(%q), ", operation)
	}
	fmt.Fprintf(b, "id: %q, reason: %q, requires: %s", deny.ID, reason, conditionLiteral(deny.Requires))
	if model.hasMatchers() {
		fmt.Fprintf(b, ", match: %s", matcherReference(model.denyMatch[index]))
	}
	fmt.Fprintln(b, "},")
}

func matcherReference(name string) string {
	if name == "" {
		return "nil"
	}
	return name
}

func writeMergeConfig(b *bytes.Buffer) {
	fmt.Fprintln(b, "func mergeRuntimeConfig(base, override cervoruntime.PolicyRuntimeConfig) cervoruntime.PolicyRuntimeConfig {")
	fmt.Fprintln(b, "out := base.Clone()")
	fmt.Fprintln(b, "if len(override.TrustedUsers) > 0 { out.TrustedUsers = append([]string(nil), override.TrustedUsers...) }")
	fmt.Fprintln(b, "if override.DefaultExecutor != \"\" { out.DefaultExecutor = override.DefaultExecutor }")
	fmt.Fprintln(b, "// The evaluator only ever arrives from the caller: DefaultConfig cannot")
	fmt.Fprintln(b, "// supply one. Dropping it here made every condition-gated policy fail to")
	fmt.Fprintln(b, "// build, because ValidateConfig then saw no evaluator at all.")
	fmt.Fprintln(b, "if override.Conditions != nil { out.Conditions = override.Conditions }")
	fmt.Fprintln(b, "for operation, target := range override.OperationTargets {")
	fmt.Fprintln(b, "if out.OperationTargets == nil { out.OperationTargets = map[cervorules.Operation]cervorules.Target{} }")
	fmt.Fprintln(b, "out.OperationTargets[operation] = target")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "for executor, fallbacks := range override.ExecutorFallbacks {")
	fmt.Fprintln(b, "if out.ExecutorFallbacks == nil { out.ExecutorFallbacks = map[cervorules.Executor][]cervorules.Executor{} }")
	fmt.Fprintln(b, "out.ExecutorFallbacks[executor] = append([]cervorules.Executor(nil), fallbacks...)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "return out")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
}

func writeEngine(b *bytes.Buffer, model renderModel) {
	fmt.Fprintln(b, "type generatedRoute struct {")
	fmt.Fprintln(b, "target cervorules.Target")
	fmt.Fprintln(b, "executor cervorules.Executor")
	fmt.Fprintln(b, "// id names the rule in a trace step; reason is what the decision carries.")
	fmt.Fprintln(b, "id string")
	fmt.Fprintln(b, "reason string")
	fmt.Fprintln(b, "requiresTrustedUser bool")
	fmt.Fprintln(b, "requires []cervorules.Condition")
	if model.hasMatchers() {
		fmt.Fprintln(b, "match ruleMatcher")
	}
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// generatedDeny is one ordered deny rule. An empty operation applies it to")
	fmt.Fprintln(b, "// every operation.")
	fmt.Fprintln(b, "type generatedDeny struct {")
	fmt.Fprintln(b, "operation cervorules.Operation")
	fmt.Fprintln(b, "id string")
	fmt.Fprintln(b, "reason string")
	fmt.Fprintln(b, "requires []cervorules.Condition")
	if model.hasMatchers() {
		fmt.Fprintln(b, "match ruleMatcher")
	}
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "type generatedEngine struct {")
	fmt.Fprintln(b, "routes map[cervorules.Operation]generatedRoute")
	fmt.Fprintln(b, "denies []generatedDeny")
	fmt.Fprintln(b, "disabledDenies map[cervorules.Operation]string")
	fmt.Fprintln(b, "trustedUsers map[string]struct{}")
	fmt.Fprintln(b, "defaultExecutor cervorules.Executor")
	fmt.Fprintln(b, "executorFallbacks map[cervorules.Executor][]cervorules.Executor")
	fmt.Fprintln(b, "conditions cervorules.Conditions")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "func (e generatedEngine) Decide(ctx context.Context, req cervorules.Request) (cervorules.DecisionResult, error) {")
	fmt.Fprintln(b, "return e.DecideWithOptions(ctx, req, cervorules.DecisionOptions{})")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	writeDecide(b, model)
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// finish assembles the decision envelope and attaches the trace steps that")
	fmt.Fprintln(b, "// were collected. Steps are only collected when trace is enabled, so an")
	fmt.Fprintln(b, "// untraced decision allocates nothing for explanation.")
	fmt.Fprintln(b, "func (e generatedEngine) finish(req cervorules.Request, decision cervorules.Decision, options cervorules.DecisionOptions, steps []cervorules.DecisionTraceStep) cervorules.DecisionResult {")
	fmt.Fprintln(b, "result := cervorules.NewDecisionResult(req, decision, cervorules.WithTrace(options.TraceEnabled()), cervorules.WithObservation(options.ObservationEnabled()))")
	fmt.Fprintln(b, "if result.Trace != nil { result.Trace.Steps = steps }")
	fmt.Fprintln(b, "return result")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// conditionsHold reports whether every required condition holds.")
	fmt.Fprintln(b, "// A condition that cannot be answered fails the decision instead of being")
	fmt.Fprintln(b, "// treated as a non-match, so an unanswerable guard never silently passes.")
	fmt.Fprintln(b, "func (e generatedEngine) conditionsHold(ctx context.Context, required []cervorules.Condition, req cervorules.Request) (bool, error) {")
	fmt.Fprintln(b, "if len(required) == 0 { return true, nil }")
	fmt.Fprintln(b, "if e.conditions == nil {")
	fmt.Fprintln(b, "return false, cervorules.Error{Code: cervorules.ErrorCodeMissingConditions, Severity: cervorules.SeverityFatal, Component: \"policy\", Field: \"conditions\", Reason: \"policy requires conditions but no evaluator is configured\"}")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "for _, condition := range required {")
	fmt.Fprintln(b, "holds, err := e.conditions.Holds(ctx, condition, req)")
	fmt.Fprintln(b, "if err != nil { return false, err }")
	fmt.Fprintln(b, "if !holds { return false, nil }")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "return true, nil")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "func (e generatedEngine) isTrustedUser(user string) bool {")
	fmt.Fprintln(b, "normalized := strings.ToLower(strings.TrimSpace(user))")
	fmt.Fprintln(b, "if normalized == \"\" { return false }")
	fmt.Fprintln(b, "_, ok := e.trustedUsers[normalized]")
	fmt.Fprintln(b, "return ok")
	fmt.Fprintln(b, "}")
}

func writeDecide(b *bytes.Buffer, model renderModel) {
	matchers := model.hasMatchers()
	fmt.Fprintln(b, "func (e generatedEngine) DecideWithOptions(ctx context.Context, req cervorules.Request, options cervorules.DecisionOptions) (cervorules.DecisionResult, error) {")
	fmt.Fprintln(b, "select {")
	fmt.Fprintln(b, "case <-ctx.Done():")
	fmt.Fprintln(b, "return cervorules.DecisionResult{}, ctx.Err()")
	fmt.Fprintln(b, "default:")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "traceEnabled := options.TraceEnabled()")
	fmt.Fprintln(b, "var steps []cervorules.DecisionTraceStep")
	if matchers {
		fmt.Fprintln(b, "// The frame is built before any rule runs, so a malformed fact cannot")
		fmt.Fprintln(b, "// hide behind an earlier rule that happened to match first.")
		fmt.Fprintln(b, "frame, err := newFactFrame(req)")
		fmt.Fprintln(b, "if err != nil { return cervorules.DecisionResult{}, err }")
	}
	fmt.Fprintln(b, "for _, deny := range e.denies {")
	fmt.Fprintln(b, "if deny.operation != \"\" && deny.operation != req.Operation { continue }")
	fmt.Fprintln(b, "applies, err := e.conditionsHold(ctx, deny.requires, req)")
	fmt.Fprintln(b, "if err != nil { return cervorules.DecisionResult{}, err }")
	fmt.Fprintln(b, "detail := \"\"")
	if matchers {
		fmt.Fprintln(b, "if applies && deny.match != nil {")
		fmt.Fprintln(b, "applies, detail, err = deny.match(ctx, e, req, frame)")
		fmt.Fprintln(b, "if err != nil { return cervorules.DecisionResult{}, err }")
		fmt.Fprintln(b, "}")
	}
	fmt.Fprintln(b, "if traceEnabled { steps = append(steps, cervorules.DecisionTraceStep{Name: deny.id, Matched: applies, Reason: detail}) }")
	fmt.Fprintln(b, "if applies {")
	fmt.Fprintln(b, "return e.finish(req, cervorules.Decision{Allow: false, Reason: deny.reason}, options, steps), nil")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "route, ok := e.routes[req.Operation]")
	fmt.Fprintln(b, "if !ok {")
	fmt.Fprintln(b, "if reason, denied := e.disabledDenies[req.Operation]; denied {")
	fmt.Fprintln(b, "return e.finish(req, cervorules.Decision{Allow: false, Reason: reason}, options, steps), nil")
	fmt.Fprintln(b, "}")
	writeLine(b, `return e.finish(req, cervorules.Decision{Allow: false, Reason: fmt.Sprintf("no route for operation %s", req.Operation)}, options, steps), nil`)
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "if route.requiresTrustedUser && !e.isTrustedUser(req.User) {")
	writeLine(b, `return e.finish(req, cervorules.Decision{Allow: false, Reason: fmt.Sprintf("operation %s requires trusted user", req.Operation)}, options, steps), nil`)
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "eligible, err := e.conditionsHold(ctx, route.requires, req)")
	fmt.Fprintln(b, "if err != nil { return cervorules.DecisionResult{}, err }")
	fmt.Fprintln(b, "routeDetail := \"\"")
	if matchers {
		fmt.Fprintln(b, "if eligible && route.match != nil {")
		fmt.Fprintln(b, "eligible, routeDetail, err = route.match(ctx, e, req, frame)")
		fmt.Fprintln(b, "if err != nil { return cervorules.DecisionResult{}, err }")
		fmt.Fprintln(b, "}")
	}
	fmt.Fprintln(b, "if traceEnabled { steps = append(steps, cervorules.DecisionTraceStep{Name: route.id, Matched: eligible, Reason: routeDetail}) }")
	fmt.Fprintln(b, "if !eligible {")
	writeLine(b, `return e.finish(req, cervorules.Decision{Allow: false, Reason: fmt.Sprintf("operation %s did not satisfy its required conditions", req.Operation)}, options, steps), nil`)
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "executor := route.executor")
	fmt.Fprintln(b, "if executor == \"\" { executor = e.defaultExecutor }")
	fmt.Fprintln(b, "decision := cervorules.Decision{Allow: true, Target: route.target, Executor: executor, FallbackExecutors: append([]cervorules.Executor(nil), e.executorFallbacks[executor]...), Reason: route.reason}")
	fmt.Fprintln(b, "return e.finish(req, decision, options, steps), nil")
	fmt.Fprintln(b, "}")
}

func generatedRouteExecutor(policy policySpec, route routeSpec) string {
	executor := normalize(route.Executor)
	if executor != "" && executor == normalize(policy.Defaults.Executor) {
		return ""
	}
	return executor
}

func writeLine(b *bytes.Buffer, line string) {
	fmt.Fprintf(b, "%s\n", line)
}
