package policygen

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"
)

func renderPolicySource(options Options, importRoot string, policy loadedPolicy, vocab loadedVocabulary) (string, error) {
	meta := metadataFor(policy, vocab)
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by cervorules-policygen; DO NOT EDIT.")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "package %s\n\n", options.PackageName)
	fmt.Fprintln(&b, "import (")
	fmt.Fprintln(&b, `"context"`)
	fmt.Fprintln(&b, `"fmt"`)
	fmt.Fprintln(&b, `"strings"`)
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "cervorules %q\n", importRoot+"/core")
	fmt.Fprintf(&b, "cervoruntime %q\n", importRoot+"/runtime")
	fmt.Fprintf(&b, "%s %q\n", options.VocabularyPackage, options.VocabularyImport)
	fmt.Fprintln(&b, ")")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "type PolicyFactory struct{}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "func NewPolicyFactory() PolicyFactory { return PolicyFactory{} }")
	fmt.Fprintln(&b)
	writeMetadata(&b, meta)
	writeDefaultConfig(&b, policy.spec)
	writeValidateConfig(&b, options.VocabularyPackage, policy.spec)
	writeBuild(&b, policy.spec)
	writeEngine(&b)
	return b.String(), nil
}

// conditionLiteral renders a rule's required condition names as Go source.
func conditionLiteral(requires []string) string {
	if len(requires) == 0 {
		return "nil"
	}
	var b strings.Builder
	b.WriteString("[]cervorules.Condition{")
	for i, name := range requires {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "cervorules.Condition(%q)", normalize(name))
	}
	b.WriteString("}")
	return b.String()
}

func writeMetadata(b *bytes.Buffer, meta PolicyMetadata) {
	fmt.Fprintln(b, "func (PolicyFactory) Metadata() cervoruntime.PolicyMetadata {")
	fmt.Fprintln(b, "return cervoruntime.PolicyMetadata{")
	fmt.Fprintf(b, "Name: %q,\n", meta.Name)
	fmt.Fprintf(b, "DSLVersion: %q,\n", meta.DSLVersion)
	fmt.Fprintf(b, "GeneratedWith: %q,\n", meta.GeneratedWith)
	fmt.Fprintf(b, "VocabularyHash: %q,\n", meta.VocabularyHash)
	fmt.Fprintf(b, "PolicyHash: %q,\n", meta.PolicyHash)
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
}

func writeDefaultConfig(b *bytes.Buffer, policy policySpec) {
	fmt.Fprintln(b, "func (PolicyFactory) DefaultConfig() cervoruntime.PolicyRuntimeConfig {")
	fmt.Fprintln(b, "return cervoruntime.PolicyRuntimeConfig{")
	if len(policy.TrustedUsers) > 0 {
		fmt.Fprintln(b, "TrustedUsers: []string{")
		for _, user := range policy.TrustedUsers {
			fmt.Fprintf(b, "%q,\n", user)
		}
		fmt.Fprintln(b, "},")
	}
	if policy.Defaults.Executor != "" {
		fmt.Fprintf(b, "DefaultExecutor: cervorules.Executor(%q),\n", normalize(policy.Defaults.Executor))
	}
	fmt.Fprintln(b, "OperationTargets: map[cervorules.Operation]cervorules.Target{")
	for _, route := range sortedRoutes(policy.Routes) {
		if route.DisabledByDefault {
			continue
		}
		fmt.Fprintf(b, "cervorules.Operation(%q): cervorules.Target(%q),\n", normalize(route.Operation), normalize(route.Target))
	}
	fmt.Fprintln(b, "},")
	fmt.Fprintln(b, "ExecutorFallbacks: map[cervorules.Executor][]cervorules.Executor{")
	for _, route := range sortedRoutes(policy.Routes) {
		if len(route.FallbackExecutors) == 0 {
			continue
		}
		fmt.Fprintf(b, "cervorules.Executor(%q): {", normalize(route.Executor))
		for _, fallback := range route.FallbackExecutors {
			fmt.Fprintf(b, "cervorules.Executor(%q),", normalize(fallback))
		}
		fmt.Fprintln(b, "},")
	}
	fmt.Fprintln(b, "},")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
}

func writeValidateConfig(b *bytes.Buffer, vocabPackage string, policy policySpec) {
	fmt.Fprintln(b, "func (PolicyFactory) ValidateConfig(cfg cervoruntime.PolicyRuntimeConfig) error {")
	fmt.Fprintf(b, "vocab := %s.Vocabulary()\n", vocabPackage)
	fmt.Fprintln(b, "var errs cervorules.Errors")
	if names := sortedConditionNames(policy); len(names) > 0 {
		// A policy that declares guards but is built without an evaluator would
		// silently allow everything those guards were meant to stop.
		fmt.Fprintln(b, "if cfg.Conditions == nil {")
		fmt.Fprintln(b, "errs = append(errs, cervorules.Error{")
		fmt.Fprintln(b, "Code: cervorules.ErrorCodeMissingConditions,")
		fmt.Fprintln(b, "Severity: cervorules.SeverityFatal,")
		fmt.Fprintln(b, "Component: \"policy\",")
		fmt.Fprintln(b, "Field: \"conditions\",")
		fmt.Fprintf(b, "Reason: %q,\n", "policy declares "+strconv.Itoa(len(names))+" condition(s) but no evaluator is configured")
		fmt.Fprintf(b, "Suggestion: %q,\n", "set PolicyRuntimeConfig.Conditions before building this policy")
		fmt.Fprintln(b, "})")
		fmt.Fprintln(b, "}")
	}
	fmt.Fprintln(b, "if cfg.DefaultExecutor != \"\" {")
	fmt.Fprintln(b, "errs = appendRuntimeValidationError(errs, vocab.ValidateExecutor(cfg.DefaultExecutor), \"defaults.executor\")")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "for operation, target := range cfg.OperationTargets {")
	writeLine(b, `operationField := fmt.Sprintf("operation_targets[%s]", operation)`)
	fmt.Fprintln(b, "errs = appendRuntimeValidationError(errs, vocab.ValidateOperation(operation), operationField)")
	fmt.Fprintln(b, "errs = appendRuntimeValidationError(errs, vocab.ValidateTarget(target), operationField+\".target\")")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "for executor, fallbacks := range cfg.ExecutorFallbacks {")
	writeLine(b, `executorField := fmt.Sprintf("executor_fallbacks[%s]", executor)`)
	fmt.Fprintln(b, "errs = appendRuntimeValidationError(errs, vocab.ValidateExecutor(executor), executorField)")
	fmt.Fprintln(b, "for i, fallback := range fallbacks {")
	writeLine(b, `errs = appendRuntimeValidationError(errs, vocab.ValidateExecutor(fallback), fmt.Sprintf("%s[%d]", executorField, i))`)
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "if len(errs) > 0 { return errs.SortStable() }")
	fmt.Fprintln(b, "return nil")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "func appendRuntimeValidationError(errs cervorules.Errors, err error, field string) cervorules.Errors {")
	fmt.Fprintln(b, "if err == nil { return errs }")
	fmt.Fprintln(b, "switch typed := err.(type) {")
	fmt.Fprintln(b, "case cervorules.Error:")
	fmt.Fprintln(b, "typed.Field = field")
	fmt.Fprintln(b, "return append(errs, typed)")
	fmt.Fprintln(b, "case cervorules.Errors:")
	fmt.Fprintln(b, "for _, item := range typed { item.Field = field; errs = append(errs, item) }")
	fmt.Fprintln(b, "return errs")
	fmt.Fprintln(b, "default:")
	fmt.Fprintln(b, "return append(errs, cervorules.Error{Code: cervorules.ErrorCodeInvalidRuntimeConfig, Field: field, Reason: err.Error()})")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
}

func writeBuild(b *bytes.Buffer, policy policySpec) {
	fmt.Fprintln(b, "func (PolicyFactory) Build(ctx context.Context, cfg cervoruntime.PolicyRuntimeConfig) (cervorules.Engine, error) {")
	fmt.Fprintln(b, "select {")
	fmt.Fprintln(b, "case <-ctx.Done():")
	fmt.Fprintln(b, "return nil, ctx.Err()")
	fmt.Fprintln(b, "default:")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "factory := PolicyFactory{}")
	fmt.Fprintln(b, "base := factory.DefaultConfig()")
	fmt.Fprintln(b, "cfg = mergeRuntimeConfig(base, cfg)")
	fmt.Fprintln(b, "if err := factory.ValidateConfig(cfg); err != nil { return nil, cervoruntime.NewPolicyBuildError(factory.Metadata(), err) }")
	fmt.Fprintln(b, "routes := map[cervorules.Operation]generatedRoute{")
	for _, route := range sortedRoutes(policy.Routes) {
		if route.DisabledByDefault {
			continue
		}
		reason := route.ID
		if strings.TrimSpace(reason) == "" {
			reason = "route matched"
		}
		fmt.Fprintf(b, "cervorules.Operation(%q): {target: cervorules.Target(%q), executor: cervorules.Executor(%q), reason: %q, requiresTrustedUser: %t, requires: %s},\n", normalize(route.Operation), normalize(route.Target), generatedRouteExecutor(policy, route), reason, route.RequiresTrustedUser, conditionLiteral(route.Requires))
	}
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "disabledRoutes := map[cervorules.Operation]generatedRoute{")
	for _, route := range sortedRoutes(policy.Routes) {
		if !route.DisabledByDefault {
			continue
		}
		reason := route.ID
		if strings.TrimSpace(reason) == "" {
			reason = "runtime override"
		}
		fmt.Fprintf(b, "cervorules.Operation(%q): {target: cervorules.Target(%q), executor: cervorules.Executor(%q), reason: %q, requiresTrustedUser: %t, requires: %s},\n", normalize(route.Operation), normalize(route.Target), generatedRouteExecutor(policy, route), reason, route.RequiresTrustedUser, conditionLiteral(route.Requires))
	}
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "trustedUsers := map[string]struct{}{}")
	fmt.Fprintln(b, "for _, user := range cfg.TrustedUsers {")
	fmt.Fprintln(b, "if normalized := strings.ToLower(strings.TrimSpace(user)); normalized != \"\" { trustedUsers[normalized] = struct{}{} }")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "for operation, target := range cfg.OperationTargets {")
	fmt.Fprintln(b, "route, ok := routes[operation]")
	fmt.Fprintln(b, "if !ok { route = disabledRoutes[operation] }")
	fmt.Fprintln(b, "route.target = target")
	fmt.Fprintln(b, "if route.executor == \"\" { route.executor = cfg.DefaultExecutor }")
	fmt.Fprintln(b, "if route.reason == \"\" { route.reason = \"runtime override\" }")
	fmt.Fprintln(b, "routes[operation] = route")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "disabledDenies := map[cervorules.Operation]string{")
	for _, route := range policy.Routes {
		if !route.DisabledByDefault {
			continue
		}
		reason := strings.TrimSpace(route.DisabledReason)
		if reason == "" {
			reason = "route disabled by default"
		}
		fmt.Fprintf(b, "cervorules.Operation(%q): %q,\n", normalize(route.Operation), reason)
	}
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "denies := map[cervorules.Operation]generatedDeny{")
	for _, deny := range policy.Denies {
		fmt.Fprintf(b, "cervorules.Operation(%q): {reason: %q, requires: %s},\n", normalize(deny.Operation), deny.Reason, conditionLiteral(deny.Requires))
	}
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "return generatedEngine{routes: routes, denies: denies, disabledDenies: disabledDenies, trustedUsers: trustedUsers, defaultExecutor: cfg.DefaultExecutor, executorFallbacks: cfg.ExecutorFallbacks, conditions: cfg.Conditions}, nil")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	writeMergeConfig(b)
}

func writeMergeConfig(b *bytes.Buffer) {
	fmt.Fprintln(b, "func mergeRuntimeConfig(base, override cervoruntime.PolicyRuntimeConfig) cervoruntime.PolicyRuntimeConfig {")
	fmt.Fprintln(b, "out := base.Clone()")
	fmt.Fprintln(b, "if len(override.TrustedUsers) > 0 { out.TrustedUsers = append([]string(nil), override.TrustedUsers...) }")
	fmt.Fprintln(b, "if override.DefaultExecutor != \"\" { out.DefaultExecutor = override.DefaultExecutor }")
	fmt.Fprintln(b, "for operation, target := range override.OperationTargets {")
	fmt.Fprintln(b, "if out.OperationTargets == nil { out.OperationTargets = map[cervorules.Operation]cervorules.Target{} }")
	fmt.Fprintln(b, "out.OperationTargets[operation] = target")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "for executor, fallbacks := range override.ExecutorFallbacks {")
	fmt.Fprintln(b, "if out.ExecutorFallbacks == nil { out.ExecutorFallbacks = map[cervorules.Executor][]cervorules.Executor{} }")
	fmt.Fprintln(b, "out.ExecutorFallbacks[executor] = append([]cervorules.Executor(nil), fallbacks...)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "return out")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
}

func writeEngine(b *bytes.Buffer) {
	fmt.Fprintln(b, "type generatedRoute struct {")
	fmt.Fprintln(b, "target cervorules.Target")
	fmt.Fprintln(b, "executor cervorules.Executor")
	fmt.Fprintln(b, "reason string")
	fmt.Fprintln(b, "requiresTrustedUser bool")
	fmt.Fprintln(b, "requires []cervorules.Condition")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "type generatedDeny struct {")
	fmt.Fprintln(b, "reason string")
	fmt.Fprintln(b, "requires []cervorules.Condition")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "type generatedEngine struct {")
	fmt.Fprintln(b, "routes map[cervorules.Operation]generatedRoute")
	fmt.Fprintln(b, "denies map[cervorules.Operation]generatedDeny")
	fmt.Fprintln(b, "disabledDenies map[cervorules.Operation]string")
	fmt.Fprintln(b, "trustedUsers map[string]struct{}")
	fmt.Fprintln(b, "defaultExecutor cervorules.Executor")
	fmt.Fprintln(b, "executorFallbacks map[cervorules.Executor][]cervorules.Executor")
	fmt.Fprintln(b, "conditions cervorules.Conditions")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "func (e generatedEngine) Decide(ctx context.Context, req cervorules.Request) (cervorules.DecisionResult, error) {")
	fmt.Fprintln(b, "return e.DecideWithOptions(ctx, req, cervorules.DecisionOptions{})")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "func (e generatedEngine) DecideWithOptions(ctx context.Context, req cervorules.Request, options cervorules.DecisionOptions) (cervorules.DecisionResult, error) {")
	fmt.Fprintln(b, "select {")
	fmt.Fprintln(b, "case <-ctx.Done():")
	fmt.Fprintln(b, "return cervorules.DecisionResult{}, ctx.Err()")
	fmt.Fprintln(b, "default:")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "if deny, denied := e.denies[req.Operation]; denied {")
	fmt.Fprintln(b, "applies, err := e.conditionsHold(ctx, deny.requires, req)")
	fmt.Fprintln(b, "if err != nil { return cervorules.DecisionResult{}, err }")
	fmt.Fprintln(b, "if applies {")
	fmt.Fprintln(b, "return cervorules.NewDecisionResult(req, cervorules.Decision{Allow: false, Reason: deny.reason}, cervorules.WithTrace(options.TraceEnabled()), cervorules.WithObservation(options.ObservationEnabled())), nil")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "route, ok := e.routes[req.Operation]")
	fmt.Fprintln(b, "if !ok {")
	fmt.Fprintln(b, "if reason, denied := e.disabledDenies[req.Operation]; denied {")
	fmt.Fprintln(b, "return cervorules.NewDecisionResult(req, cervorules.Decision{Allow: false, Reason: reason}, cervorules.WithTrace(options.TraceEnabled()), cervorules.WithObservation(options.ObservationEnabled())), nil")
	fmt.Fprintln(b, "}")
	writeLine(b, `return cervorules.NewDecisionResult(req, cervorules.Decision{Allow: false, Reason: fmt.Sprintf("no route for operation %s", req.Operation)}, cervorules.WithTrace(options.TraceEnabled()), cervorules.WithObservation(options.ObservationEnabled())), nil`)
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "if route.requiresTrustedUser && !e.isTrustedUser(req.User) {")
	writeLine(b, `return cervorules.NewDecisionResult(req, cervorules.Decision{Allow: false, Reason: fmt.Sprintf("operation %s requires trusted user", req.Operation)}, cervorules.WithTrace(options.TraceEnabled()), cervorules.WithObservation(options.ObservationEnabled())), nil`)
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "eligible, err := e.conditionsHold(ctx, route.requires, req)")
	fmt.Fprintln(b, "if err != nil { return cervorules.DecisionResult{}, err }")
	fmt.Fprintln(b, "if !eligible {")
	writeLine(b, `return cervorules.NewDecisionResult(req, cervorules.Decision{Allow: false, Reason: fmt.Sprintf("operation %s did not satisfy its required conditions", req.Operation)}, cervorules.WithTrace(options.TraceEnabled()), cervorules.WithObservation(options.ObservationEnabled())), nil`)
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "executor := route.executor")
	fmt.Fprintln(b, "if executor == \"\" { executor = e.defaultExecutor }")
	fmt.Fprintln(b, "decision := cervorules.Decision{Allow: true, Target: route.target, Executor: executor, FallbackExecutors: append([]cervorules.Executor(nil), e.executorFallbacks[executor]...), Reason: route.reason}")
	fmt.Fprintln(b, "return cervorules.NewDecisionResult(req, decision, cervorules.WithTrace(options.TraceEnabled()), cervorules.WithObservation(options.ObservationEnabled())), nil")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// conditionsHold reports whether every required condition holds.")
	fmt.Fprintln(b, "// A condition that cannot be answered fails the decision instead of being")
	fmt.Fprintln(b, "// treated as a non-match, so an unanswerable guard never silently passes.")
	fmt.Fprintln(b, "func (e generatedEngine) conditionsHold(ctx context.Context, required []cervorules.Condition, req cervorules.Request) (bool, error) {")
	fmt.Fprintln(b, "if len(required) == 0 { return true, nil }")
	fmt.Fprintln(b, "if e.conditions == nil {")
	fmt.Fprintln(b, "return false, cervorules.Error{Code: cervorules.ErrorCodeMissingConditions, Severity: cervorules.SeverityFatal, Component: \"policy\", Field: \"conditions\", Reason: \"policy requires conditions but no evaluator is configured\"}")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "for _, condition := range required {")
	fmt.Fprintln(b, "holds, err := e.conditions.Holds(ctx, condition, req)")
	fmt.Fprintln(b, "if err != nil { return false, err }")
	fmt.Fprintln(b, "if !holds { return false, nil }")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b, "return true, nil")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "func (e generatedEngine) isTrustedUser(user string) bool {")
	fmt.Fprintln(b, "normalized := strings.ToLower(strings.TrimSpace(user))")
	fmt.Fprintln(b, "if normalized == \"\" { return false }")
	fmt.Fprintln(b, "_, ok := e.trustedUsers[normalized]")
	fmt.Fprintln(b, "return ok")
	fmt.Fprintln(b, "}")
}

func generatedRouteExecutor(policy policySpec, route routeSpec) string {
	executor := normalize(route.Executor)
	if executor != "" && executor == normalize(policy.Defaults.Executor) {
		return ""
	}
	return executor
}

func writeLine(b *bytes.Buffer, line string) {
	fmt.Fprintf(b, "%s\n", line)
}
