package policygen

import (
	"bytes"
	"fmt"
	"strings"
)

func renderTestSource(options Options, importRoot string, policy loadedPolicy) (string, error) {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by cervorules-policygen; DO NOT EDIT.")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "package %s\n\n", options.PackageName)
	fmt.Fprintln(&b, "import (")
	fmt.Fprintln(&b, `"context"`)
	if generatedTestsNeedStrings(policy.spec.Tests) {
		fmt.Fprintln(&b, `"strings"`)
	}
	fmt.Fprintln(&b, `"testing"`)
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "cervorules %q\n", importRoot+"/core")
	fmt.Fprintln(&b, ")")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "func TestGeneratedPolicyFactory(t *testing.T) {")
	fmt.Fprintln(&b, "factory := NewPolicyFactory()")
	fmt.Fprintln(&b, "cfg := factory.DefaultConfig()")
	writeTestLine(&b, `if err := factory.ValidateConfig(cfg); err != nil { t.Fatalf("validate default config: %v", err) }`)
	fmt.Fprintln(&b, "engine, err := factory.Build(context.Background(), cfg)")
	writeTestLine(&b, `if err != nil { t.Fatalf("build policy: %v", err) }`)
	fmt.Fprintln(&b, "metadata := factory.Metadata()")
	writeTestLine(&b, `if metadata.Name == "" || metadata.DSLVersion == "" || metadata.VocabularyHash == "" || metadata.PolicyHash == "" { t.Fatalf("metadata incomplete: %#v", metadata) }`)
	for i, test := range policy.spec.Tests {
		writeGeneratedTestCase(&b, i, test)
	}
	fmt.Fprintln(&b, "}")
	return b.String(), nil
}

func generatedTestsNeedStrings(tests []testSpec) bool {
	for _, test := range tests {
		if test.Expect.ReasonContains != "" {
			return true
		}
	}
	return false
}

func writeGeneratedTestCase(b *bytes.Buffer, index int, test testSpec) {
	name := test.Name
	if strings.TrimSpace(name) == "" {
		name = fmt.Sprintf("case-%d", index+1)
	}
	fmt.Fprintf(b, "t.Run(%q, func(t *testing.T) {\n", name)
	fmt.Fprintln(b, "result, err := engine.Decide(context.Background(), cervorules.Request{")
	if test.Request.ID != "" {
		fmt.Fprintf(b, "ID: %q,\n", test.Request.ID)
	}
	if test.Request.User != "" {
		fmt.Fprintf(b, "User: %q,\n", test.Request.User)
	}
	if test.Request.Channel != "" {
		fmt.Fprintf(b, "Channel: %q,\n", test.Request.Channel)
	}
	fmt.Fprintf(b, "Operation: cervorules.Operation(%q),\n", normalize(test.Request.Operation))
	if len(test.Request.Metadata) > 0 {
		fmt.Fprintln(b, "Metadata: map[string]string{")
		for key, value := range test.Request.Metadata {
			fmt.Fprintf(b, "%q: %q,\n", key, value)
		}
		fmt.Fprintln(b, "},")
	}
	fmt.Fprintln(b, "})")
	writeTestLine(b, `if err != nil { t.Fatalf("decide: %v", err) }`)
	if test.Expect.Allow != nil {
		fmt.Fprintf(b, "if result.Decision.Allow != %t { t.Fatalf(\"allow mismatch: %%#v\", result.Decision) }\n", *test.Expect.Allow)
	}
	if test.Expect.Target != "" {
		fmt.Fprintf(b, "if result.Decision.Target != cervorules.Target(%q) { t.Fatalf(\"target mismatch: %%#v\", result.Decision) }\n", normalize(test.Expect.Target))
	}
	if test.Expect.Executor != "" {
		fmt.Fprintf(b, "if result.Decision.Executor != cervorules.Executor(%q) { t.Fatalf(\"executor mismatch: %%#v\", result.Decision) }\n", normalize(test.Expect.Executor))
	}
	if len(test.Expect.FallbackExecutors) > 0 {
		fmt.Fprintf(b, "if len(result.Decision.FallbackExecutors) != %d { t.Fatalf(\"fallback executor mismatch: %%#v\", result.Decision) }\n", len(test.Expect.FallbackExecutors))
		for i, executor := range test.Expect.FallbackExecutors {
			fmt.Fprintf(b, "if result.Decision.FallbackExecutors[%d] != cervorules.Executor(%q) { t.Fatalf(\"fallback executor mismatch: %%#v\", result.Decision) }\n", i, normalize(executor))
		}
	}
	if test.Expect.Reason != "" {
		fmt.Fprintf(b, "if result.Decision.Reason != %q { t.Fatalf(\"reason mismatch: %%#v\", result.Decision) }\n", test.Expect.Reason)
	}
	if test.Expect.ReasonContains != "" {
		fmt.Fprintf(b, "if !strings.Contains(result.Decision.Reason, %q) { t.Fatalf(\"reason mismatch: %%#v\", result.Decision) }\n", test.Expect.ReasonContains)
	}
	fmt.Fprintln(b, "})")
}

func writeTestLine(b *bytes.Buffer, line string) {
	fmt.Fprintf(b, "%s\n", line)
}
