// Code generated by cervorules-policygen; DO NOT EDIT.

package fuzzpolicy

import (
	"context"
	"fmt"
	"math"
	"strconv"
	"strings"

	cervorules "github.com/cervantesh/cervo-rules/v3/core"
	vocab "github.com/cervantesh/cervo-rules/v3/internal/fuzzpolicy/vocab"
	cervoruntime "github.com/cervantesh/cervo-rules/v3/runtime"
)

type PolicyFactory struct{}

func NewPolicyFactory() PolicyFactory { return PolicyFactory{} }

func (PolicyFactory) Metadata() cervoruntime.PolicyMetadata {
	return cervoruntime.PolicyMetadata{
		Name:           "predicate-composition.v3",
		DSLVersion:     "cervorules.policy.v3",
		GeneratedWith:  "cervorules-policygen/v3",
		VocabularyHash: "b27c5f0ff62d4357861bbfb8d9a1526b8fdac3395d7df1a30bfa919eeff0aa4b",
		PolicyHash:     "6bbdbdfbc60f38e0df6dbcddffcaebe606c10f8a7de91c56504d96cf0488d52c",
	}
}

func (PolicyFactory) DefaultConfig() cervoruntime.PolicyRuntimeConfig {
	return cervoruntime.PolicyRuntimeConfig{
		DefaultExecutor: cervorules.Executor("standard_executor"),
		OperationTargets: map[cervorules.Operation]cervorules.Target{
			cervorules.Operation("deploy"):         cervorules.Target("deployer"),
			cervorules.Operation("message_create"): cervorules.Target("message_worker"),
		},
		ExecutorFallbacks: map[cervorules.Executor][]cervorules.Executor{},
	}
}

func (PolicyFactory) ValidateConfig(cfg cervoruntime.PolicyRuntimeConfig) error {
	vocab := vocab.Vocabulary()
	var errs cervorules.Errors
	if cfg.DefaultExecutor != "" {
		errs = appendRuntimeValidationError(errs, vocab.ValidateExecutor(cfg.DefaultExecutor), "defaults.executor")
	}
	for operation, target := range cfg.OperationTargets {
		operationField := fmt.Sprintf("operation_targets[%s]", operation)
		errs = appendRuntimeValidationError(errs, vocab.ValidateOperation(operation), operationField)
		errs = appendRuntimeValidationError(errs, vocab.ValidateTarget(target), operationField+".target")
	}
	for executor, fallbacks := range cfg.ExecutorFallbacks {
		executorField := fmt.Sprintf("executor_fallbacks[%s]", executor)
		errs = appendRuntimeValidationError(errs, vocab.ValidateExecutor(executor), executorField)
		for i, fallback := range fallbacks {
			errs = appendRuntimeValidationError(errs, vocab.ValidateExecutor(fallback), fmt.Sprintf("%s[%d]", executorField, i))
		}
	}
	if len(errs) > 0 {
		return errs.SortStable()
	}
	return nil
}

func appendRuntimeValidationError(errs cervorules.Errors, err error, field string) cervorules.Errors {
	if err == nil {
		return errs
	}
	switch typed := err.(type) {
	case cervorules.Error:
		typed.Field = field
		return append(errs, typed)
	case cervorules.Errors:
		for _, item := range typed {
			item.Field = field
			errs = append(errs, item)
		}
		return errs
	default:
		return append(errs, cervorules.Error{Code: cervorules.ErrorCodeInvalidRuntimeConfig, Field: field, Reason: err.Error()})
	}
}

func (PolicyFactory) Build(ctx context.Context, cfg cervoruntime.PolicyRuntimeConfig) (cervorules.Engine, error) {
	select {
	case <-ctx.Done():
		return nil, ctx.Err()
	default:
	}
	factory := PolicyFactory{}
	base := factory.DefaultConfig()
	cfg = mergeRuntimeConfig(base, cfg)
	if err := factory.ValidateConfig(cfg); err != nil {
		return nil, cervoruntime.NewPolicyBuildError(factory.Metadata(), err)
	}
	routes := map[cervorules.Operation]generatedRoute{
		cervorules.Operation("deploy"):         {target: cervorules.Target("deployer"), executor: cervorules.Executor(""), id: "deploy", reason: "deploy", requiresTrustedUser: false, requires: nil, match: nil},
		cervorules.Operation("message_create"): {target: cervorules.Target("message_worker"), executor: cervorules.Executor(""), id: "message_create", reason: "message_create", requiresTrustedUser: false, requires: nil, match: nil},
	}
	disabledRoutes := map[cervorules.Operation]generatedRoute{}
	trustedUsers := map[string]struct{}{}
	for _, user := range cfg.TrustedUsers {
		if normalized := strings.ToLower(strings.TrimSpace(user)); normalized != "" {
			trustedUsers[normalized] = struct{}{}
		}
	}
	for operation, target := range cfg.OperationTargets {
		route, ok := routes[operation]
		if !ok {
			route = disabledRoutes[operation]
		}
		route.target = target
		if route.executor == "" {
			route.executor = cfg.DefaultExecutor
		}
		if route.id == "" {
			route.id = string(operation)
		}
		if route.reason == "" {
			route.reason = "runtime override"
		}
		routes[operation] = route
	}
	disabledDenies := map[cervorules.Operation]string{}
	denies := []generatedDeny{
		{id: "deny-change-freeze", reason: "a change freeze is in effect", requires: nil, match: matchRule0DenyChangeFreeze},
		{operation: cervorules.Operation("message_create"), id: "deny-unhealthy-target", reason: "the worker is saturated, or it is burning its error budget", requires: nil, match: matchRule1DenyUnhealthyTarget},
		{operation: cervorules.Operation("deploy"), id: "deny-unreviewed-production-deploy", reason: "a production deploy needs a healthy target", requires: nil, match: matchRule2DenyUnreviewedProductionDeploy},
	}
	return generatedEngine{routes: routes, denies: denies, disabledDenies: disabledDenies, trustedUsers: trustedUsers, defaultExecutor: cfg.DefaultExecutor, executorFallbacks: cfg.ExecutorFallbacks, conditions: cfg.Conditions}, nil
}

func mergeRuntimeConfig(base, override cervoruntime.PolicyRuntimeConfig) cervoruntime.PolicyRuntimeConfig {
	out := base.Clone()
	if len(override.TrustedUsers) > 0 {
		out.TrustedUsers = append([]string(nil), override.TrustedUsers...)
	}
	if override.DefaultExecutor != "" {
		out.DefaultExecutor = override.DefaultExecutor
	}
	// The evaluator only ever arrives from the caller: DefaultConfig cannot
	// supply one. Dropping it here made every condition-gated policy fail to
	// build, because ValidateConfig then saw no evaluator at all.
	if override.Conditions != nil {
		out.Conditions = override.Conditions
	}
	for operation, target := range override.OperationTargets {
		if out.OperationTargets == nil {
			out.OperationTargets = map[cervorules.Operation]cervorules.Target{}
		}
		out.OperationTargets[operation] = target
	}
	for executor, fallbacks := range override.ExecutorFallbacks {
		if out.ExecutorFallbacks == nil {
			out.ExecutorFallbacks = map[cervorules.Executor][]cervorules.Executor{}
		}
		out.ExecutorFallbacks[executor] = append([]cervorules.Executor(nil), fallbacks...)
	}
	return out
}

// factFrame holds the facts this policy reads, parsed once per decision.
type factFrame struct {
	factChangeFreeze   bool
	factEnvironment    string
	factErrorBudgetPct float64
	factErrorRatePct   float64
	factQueueDepth     int64
}

// newFactFrame parses every fact this policy reads before any rule runs.
// A fact that is absent, unparseable, non-finite or outside its declared
// bounds fails the decision with a structured error. It never reports a
// predicate as unsatisfied, which would read as "the guard ran and found
// nothing wrong".
func newFactFrame(req cervorules.Request) (factFrame, error) {
	var frame factFrame
	var err error
	if frame.factChangeFreeze, err = factBoolValue(req, "change_freeze", factBoolBounds{}); err != nil {
		return factFrame{}, err
	}
	if frame.factEnvironment, err = factEnumValue(req, "environment", []string{"dev", "staging", "production"}, factStringBounds{}); err != nil {
		return factFrame{}, err
	}
	if frame.factErrorBudgetPct, err = factNumberValue(req, "error_budget_pct", factNumberBounds{hasDefault: true, def: 1, hasMin: true, min: 0, hasMax: true, max: 100}); err != nil {
		return factFrame{}, err
	}
	if frame.factErrorRatePct, err = factNumberValue(req, "error_rate_pct", factNumberBounds{hasMin: true, min: 0, hasMax: true, max: 100}); err != nil {
		return factFrame{}, err
	}
	if frame.factQueueDepth, err = factIntegerValue(req, "queue_depth", factIntegerBounds{hasMin: true, min: 0}); err != nil {
		return factFrame{}, err
	}
	return frame, nil
}

// factRawValue reports the trimmed metadata value for a fact. A blank value
// counts as absent: an empty string is not an answer.
func factRawValue(req cervorules.Request, name string) (string, bool) {
	raw, ok := req.Metadata[name]
	if !ok {
		return "", false
	}
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "", false
	}
	return raw, true
}

func missingFactError(name string) error {
	return cervorules.Error{
		Code:       cervorules.ErrorCodeMissingFact,
		Severity:   cervorules.SeverityFatal,
		Component:  "policy",
		Field:      "facts." + name,
		Reason:     "fact is absent from request metadata and the policy declares no default",
		Suggestion: "supply the fact in Request.Metadata, or declare a default for it in the policy",
	}
}

// invalidFactError marks the observed value sensitive: only the caller knows
// whether a fact carries secrets, so it is withheld from serialization by
// default and still available in process.
func invalidFactError(name string, value string, reason string) error {
	return cervorules.Error{
		Code:      cervorules.ErrorCodeInvalidFact,
		Severity:  cervorules.SeverityFatal,
		Component: "policy",
		Field:     "facts." + name,
		Value:     value,
		Reason:    reason,
		Sensitive: true,
	}
}

type factNumberBounds struct {
	hasDefault bool
	def        float64
	hasMin     bool
	min        float64
	hasMax     bool
	max        float64
}

func factNumberValue(req cervorules.Request, name string, bounds factNumberBounds) (float64, error) {
	raw, ok := factRawValue(req, name)
	if !ok {
		if bounds.hasDefault {
			return bounds.def, nil
		}
		return 0, missingFactError(name)
	}
	value, err := strconv.ParseFloat(raw, 64)
	if err != nil {
		return 0, invalidFactError(name, raw, "fact is not a number")
	}
	// ParseFloat accepts "NaN" and "Inf". A non-finite value passes every
	// comparison in this policy without matching any of them, so it would
	// slip through the deny rules and land on the allow path.
	if math.IsNaN(value) || math.IsInf(value, 0) {
		return 0, invalidFactError(name, raw, "fact is not a finite number")
	}
	if bounds.hasMin && value < bounds.min {
		return 0, invalidFactError(name, raw, "fact is below its declared minimum")
	}
	if bounds.hasMax && value > bounds.max {
		return 0, invalidFactError(name, raw, "fact is above its declared maximum")
	}
	return value, nil
}

type factIntegerBounds struct {
	hasDefault bool
	def        int64
	hasMin     bool
	min        int64
	hasMax     bool
	max        int64
}

func factIntegerValue(req cervorules.Request, name string, bounds factIntegerBounds) (int64, error) {
	raw, ok := factRawValue(req, name)
	if !ok {
		if bounds.hasDefault {
			return bounds.def, nil
		}
		return 0, missingFactError(name)
	}
	value, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		return 0, invalidFactError(name, raw, "fact is not an integer")
	}
	if bounds.hasMin && value < bounds.min {
		return 0, invalidFactError(name, raw, "fact is below its declared minimum")
	}
	if bounds.hasMax && value > bounds.max {
		return 0, invalidFactError(name, raw, "fact is above its declared maximum")
	}
	return value, nil
}

type factBoolBounds struct {
	hasDefault bool
	def        bool
}

func factBoolValue(req cervorules.Request, name string, bounds factBoolBounds) (bool, error) {
	raw, ok := factRawValue(req, name)
	if !ok {
		if bounds.hasDefault {
			return bounds.def, nil
		}
		return false, missingFactError(name)
	}
	value, err := strconv.ParseBool(raw)
	if err != nil {
		return false, invalidFactError(name, raw, "fact is not a bool")
	}
	return value, nil
}

type factStringBounds struct {
	hasDefault bool
	def        string
}

func factEnumValue(req cervorules.Request, name string, allowed []string, bounds factStringBounds) (string, error) {
	raw, ok := factRawValue(req, name)
	if !ok {
		if bounds.hasDefault {
			return bounds.def, nil
		}
		return "", missingFactError(name)
	}
	value := strings.ToLower(raw)
	for _, candidate := range allowed {
		if value == candidate {
			return value, nil
		}
	}
	return "", invalidFactError(name, raw, "fact is outside its declared domain")
}

// ruleMatcher is a compiled predicate. It reports whether the rule matched
// and which leaf decided it, so a trace step can name the reason.
type ruleMatcher func(ctx context.Context, e generatedEngine, req cervorules.Request, f factFrame) (bool, string, error)

// all(change_freeze is_true, environment eq production)
func matchRule0DenyChangeFreeze(ctx context.Context, e generatedEngine, req cervorules.Request, f factFrame) (bool, string, error) {
	if !(f.factChangeFreeze) {
		return false, "", nil
	}
	if !(f.factEnvironment == "production") {
		return false, "", nil
	}
	return true, "all(change_freeze is_true, environment eq production)", nil
}

// any(queue_depth gte 10000, error_rate_pct gt error_budget_pct)
func matchRule1DenyUnhealthyTarget(ctx context.Context, e generatedEngine, req cervorules.Request, f factFrame) (bool, string, error) {
	if f.factQueueDepth >= 10000 {
		return true, "queue_depth gte 10000", nil
	}
	if f.factErrorRatePct > f.factErrorBudgetPct {
		return true, "error_rate_pct gt error_budget_pct", nil
	}
	return false, "", nil
}

// not(error_rate_pct lt 0.5)
func matchRule2DenyUnreviewedProductionDeployNode1(ctx context.Context, e generatedEngine, req cervorules.Request, f factFrame) (bool, string, error) {
	if f.factErrorRatePct < 0.5 {
		return false, "", nil
	}
	return true, "not(error_rate_pct lt 0.5)", nil
}

// all(environment eq production, not(error_rate_pct lt 0.5))
func matchRule2DenyUnreviewedProductionDeploy(ctx context.Context, e generatedEngine, req cervorules.Request, f factFrame) (bool, string, error) {
	if !(f.factEnvironment == "production") {
		return false, "", nil
	}
	ok1, _, err1 := matchRule2DenyUnreviewedProductionDeployNode1(ctx, e, req, f)
	if err1 != nil {
		return false, "", err1
	}
	if !ok1 {
		return false, "", nil
	}
	return true, "all(environment eq production, not(error_rate_pct lt 0.5))", nil
}

type generatedRoute struct {
	target   cervorules.Target
	executor cervorules.Executor
	// id names the rule in a trace step; reason is what the decision carries.
	id                  string
	reason              string
	requiresTrustedUser bool
	requires            []cervorules.Condition
	match               ruleMatcher
}

// generatedDeny is one ordered deny rule. An empty operation applies it to
// every operation.
type generatedDeny struct {
	operation cervorules.Operation
	id        string
	reason    string
	requires  []cervorules.Condition
	match     ruleMatcher
}

type generatedEngine struct {
	routes            map[cervorules.Operation]generatedRoute
	denies            []generatedDeny
	disabledDenies    map[cervorules.Operation]string
	trustedUsers      map[string]struct{}
	defaultExecutor   cervorules.Executor
	executorFallbacks map[cervorules.Executor][]cervorules.Executor
	conditions        cervorules.Conditions
}

func (e generatedEngine) Decide(ctx context.Context, req cervorules.Request) (cervorules.DecisionResult, error) {
	return e.DecideWithOptions(ctx, req, cervorules.DecisionOptions{})
}

func (e generatedEngine) DecideWithOptions(ctx context.Context, req cervorules.Request, options cervorules.DecisionOptions) (cervorules.DecisionResult, error) {
	select {
	case <-ctx.Done():
		return cervorules.DecisionResult{}, ctx.Err()
	default:
	}
	traceEnabled := options.TraceEnabled()
	var steps []cervorules.DecisionTraceStep
	// The frame is built before any rule runs, so a malformed fact cannot
	// hide behind an earlier rule that happened to match first.
	frame, err := newFactFrame(req)
	if err != nil {
		return cervorules.DecisionResult{}, err
	}
	for _, deny := range e.denies {
		if deny.operation != "" && deny.operation != req.Operation {
			continue
		}
		applies, err := e.conditionsHold(ctx, deny.requires, req)
		if err != nil {
			return cervorules.DecisionResult{}, err
		}
		detail := ""
		if applies && deny.match != nil {
			applies, detail, err = deny.match(ctx, e, req, frame)
			if err != nil {
				return cervorules.DecisionResult{}, err
			}
		}
		if traceEnabled {
			steps = append(steps, cervorules.DecisionTraceStep{Name: deny.id, Matched: applies, Reason: detail})
		}
		if applies {
			return e.finish(req, cervorules.Decision{Allow: false, Reason: deny.reason}, options, steps), nil
		}
	}
	route, ok := e.routes[req.Operation]
	if !ok {
		if reason, denied := e.disabledDenies[req.Operation]; denied {
			return e.finish(req, cervorules.Decision{Allow: false, Reason: reason}, options, steps), nil
		}
		return e.finish(req, cervorules.Decision{Allow: false, Reason: fmt.Sprintf("no route for operation %s", req.Operation)}, options, steps), nil
	}
	if route.requiresTrustedUser && !e.isTrustedUser(req.User) {
		return e.finish(req, cervorules.Decision{Allow: false, Reason: fmt.Sprintf("operation %s requires trusted user", req.Operation)}, options, steps), nil
	}
	eligible, err := e.conditionsHold(ctx, route.requires, req)
	if err != nil {
		return cervorules.DecisionResult{}, err
	}
	routeDetail := ""
	if eligible && route.match != nil {
		eligible, routeDetail, err = route.match(ctx, e, req, frame)
		if err != nil {
			return cervorules.DecisionResult{}, err
		}
	}
	if traceEnabled {
		steps = append(steps, cervorules.DecisionTraceStep{Name: route.id, Matched: eligible, Reason: routeDetail})
	}
	if !eligible {
		return e.finish(req, cervorules.Decision{Allow: false, Reason: fmt.Sprintf("operation %s did not satisfy its required conditions", req.Operation)}, options, steps), nil
	}
	executor := route.executor
	if executor == "" {
		executor = e.defaultExecutor
	}
	decision := cervorules.Decision{Allow: true, Target: route.target, Executor: executor, FallbackExecutors: append([]cervorules.Executor(nil), e.executorFallbacks[executor]...), Reason: route.reason}
	return e.finish(req, decision, options, steps), nil
}

// finish assembles the decision envelope and attaches the trace steps that
// were collected. Steps are only collected when trace is enabled, so an
// untraced decision allocates nothing for explanation.
func (e generatedEngine) finish(req cervorules.Request, decision cervorules.Decision, options cervorules.DecisionOptions, steps []cervorules.DecisionTraceStep) cervorules.DecisionResult {
	result := cervorules.NewDecisionResult(req, decision, cervorules.WithTrace(options.TraceEnabled()), cervorules.WithObservation(options.ObservationEnabled()))
	if result.Trace != nil {
		result.Trace.Steps = steps
	}
	return result
}

// conditionsHold reports whether every required condition holds.
// A condition that cannot be answered fails the decision instead of being
// treated as a non-match, so an unanswerable guard never silently passes.
func (e generatedEngine) conditionsHold(ctx context.Context, required []cervorules.Condition, req cervorules.Request) (bool, error) {
	if len(required) == 0 {
		return true, nil
	}
	if e.conditions == nil {
		return false, cervorules.Error{Code: cervorules.ErrorCodeMissingConditions, Severity: cervorules.SeverityFatal, Component: "policy", Field: "conditions", Reason: "policy requires conditions but no evaluator is configured"}
	}
	for _, condition := range required {
		holds, err := e.conditions.Holds(ctx, condition, req)
		if err != nil {
			return false, err
		}
		if !holds {
			return false, nil
		}
	}
	return true, nil
}

func (e generatedEngine) isTrustedUser(user string) bool {
	normalized := strings.ToLower(strings.TrimSpace(user))
	if normalized == "" {
		return false
	}
	_, ok := e.trustedUsers[normalized]
	return ok
}
