package metamorphic

import (
	"fmt"
	"strings"
)

// driverSource emits the test that runs inside the temporary module. It has to
// live there rather than here: the generated policies are compiled in a module
// of their own, so nothing in this repository can import them.
func driverSource(families []familySource) string {
	var b strings.Builder

	b.WriteString(`// Code generated by internal/metamorphic; DO NOT EDIT.

package driver

import (
	"context"
	"errors"
	"testing"

	core "github.com/cervantesh/cervo-rules/v3/core"
	rt "github.com/cervantesh/cervo-rules/v3/runtime"
`)
	for _, family := range families {
		for _, variant := range []string{variantBase, variantExtraDeny, variantInert, variantDeMorgan} {
			fmt.Fprintf(&b, "\t%s%s \"example.test/generated/%s%s\"\n", family.Package, variant, family.Package, variant)
		}
	}
	b.WriteString(")\n")

	fmt.Fprintf(&b, "\nconst absent = %q\n", absentClass)

	b.WriteString(`
type factSpec struct {
	Name    string
	Classes []string
}

type family struct {
	Name       string
	Operations []string
	Facts      []factSpec
	Base       core.Engine
	ExtraDeny  core.Engine
	Inert      core.Engine
	DeMorgan     core.Engine
}

func build(t *testing.T, factory rt.PolicyFactory) core.Engine {
	t.Helper()
	engine, err := factory.Build(context.Background(), rt.PolicyRuntimeConfig{})
	if err != nil {
		t.Fatalf("build engine: %v", err)
	}
	return engine
}

func allFamilies(t *testing.T) []family {
	t.Helper()
	return []family{
`)
	for _, family := range families {
		fmt.Fprintf(&b, "\t\t{\n\t\t\tName: %q,\n", family.Package)
		fmt.Fprintf(&b, "\t\t\tOperations: []string{%s},\n", quoteAll(family.Operations))
		b.WriteString("\t\t\tFacts: []factSpec{\n")
		for _, fact := range family.Facts {
			fmt.Fprintf(&b, "\t\t\t\t{Name: %q, Classes: []string{%s}},\n", fact.Name, quoteAll(fact.Classes))
		}
		b.WriteString("\t\t\t},\n")
		for _, variant := range []string{variantBase, variantExtraDeny, variantInert, variantDeMorgan} {
			field := map[string]string{
				variantBase: "Base", variantExtraDeny: "ExtraDeny",
				variantInert: "Inert", variantDeMorgan: "DeMorgan",
			}[variant]
			fmt.Fprintf(&b, "\t\t\t%s: build(t, %s%s.NewPolicyFactory()),\n", field, family.Package, variant)
		}
		b.WriteString("\t\t},\n")
	}
	b.WriteString("\t}\n}\n")

	b.WriteString(`
// errorCode reduces a decision failure to the code a caller would branch on.
// "" means the decision succeeded.
func errorCode(err error) string {
	if err == nil {
		return ""
	}
	var structured core.Error
	if errors.As(err, &structured) {
		return string(structured.Code)
	}
	return "unstructured:" + err.Error()
}

func sameDecision(a, b core.Decision) bool {
	return a.Allow == b.Allow && a.Target == b.Target && a.Executor == b.Executor && a.Reason == b.Reason
}

func describe(operation string, metadata map[string]string) string {
	out := operation + " {"
	for key, value := range metadata {
		out += " " + key + "=" + value
	}
	return out + " }"
}

// enumerate walks every combination of every fact's equivalence classes. It is
// a full cartesian product, not a sample: within the class lattice the result
// is exhaustive.
func enumerate(facts []factSpec, index int, metadata map[string]string, visit func(map[string]string)) {
	if index == len(facts) {
		visit(metadata)
		return
	}
	fact := facts[index]
	for _, class := range fact.Classes {
		if class == absent {
			delete(metadata, fact.Name)
		} else {
			metadata[fact.Name] = class
		}
		enumerate(facts, index+1, metadata, visit)
	}
	delete(metadata, fact.Name)
}

func TestMetamorphicProperties(t *testing.T) {
	ctx := context.Background()

	for _, fam := range allFamilies(t) {
		fam := fam
		t.Run(fam.Name, func(t *testing.T) {
			requests := 0
			failures := 0
			fail := func(format string, args ...any) {
				failures++
				if failures <= 5 {
					t.Errorf(format, args...)
				}
			}

			for _, operation := range fam.Operations {
				enumerate(fam.Facts, 0, map[string]string{}, func(metadata map[string]string) {
					if failures > 5 {
						return
					}
					requests++
					request := func() core.Request {
						copied := make(map[string]string, len(metadata))
						for key, value := range metadata {
							copied[key] = value
						}
						return core.Request{Operation: core.Operation(operation), Metadata: copied}
					}
					where := describe(operation, metadata)

					base, baseErr := fam.Base.Decide(ctx, request())

					// P1: the same request twice gives the same answer. A map
					// iterated anywhere in the decision path breaks this.
					again, againErr := fam.Base.Decide(ctx, request())
					if errorCode(baseErr) != errorCode(againErr) || !sameDecision(base.Decision, again.Decision) {
						fail("P1 determinism: two identical requests disagreed at %s", where)
					}

					// P2: an unusable fact fails the decision, and it fails with
					// a code a caller can branch on.
					switch code := errorCode(baseErr); code {
					case "", string(core.ErrorCodeMissingFact), string(core.ErrorCodeInvalidFact):
					default:
						fail("P2 fail-closed: unexpected error code %q at %s", code, where)
					}

					// P4: a rule that cannot hold cannot change a decision.
					//
					// It is not stated as "nothing changes at all". A rule is
					// what makes the engine read a fact, so an unsatisfiable
					// rule mentioning a fact no other rule reads does make that
					// fact required, and a request that omitted it stops being
					// decidable. That is recorded as a gap; here the property is
					// the part that must hold regardless: it may never relax.
					inert, inertErr := fam.Inert.Decide(ctx, request())
					if baseErr != nil && inertErr == nil {
						fail("P4 inertness: an unsatisfiable rule turned a refusal into a decision at %s\n  base err=%q\n  inert: %+v",
							where, errorCode(baseErr), inert.Decision)
					}
					if baseErr == nil && inertErr == nil && !sameDecision(inert.Decision, base.Decision) {
						fail("P4 inertness: an unsatisfiable rule changed the decision at %s\n  base:  %+v\n  inert: %+v",
							where, base.Decision, inert.Decision)
					}

					// P5: the De Morgan dual of a rule decides exactly as the rule.
					demorgan, demorganErr := fam.DeMorgan.Decide(ctx, request())
					if errorCode(demorganErr) != errorCode(baseErr) || (baseErr == nil && !sameDecision(demorgan.Decision, base.Decision)) {
						fail("P5 De Morgan: the dual disagreed with the original at %s\n  base:   %+v err=%q\n  demorgan: %+v err=%q",
							where, base.Decision, errorCode(baseErr), demorgan.Decision, errorCode(demorganErr))
					}

					// P3: appending a deny can remove an allow and never create
					// one, and an earlier matching deny keeps its reason because
					// the first match wins.
					extra, extraErr := fam.ExtraDeny.Decide(ctx, request())
					if baseErr == nil && extraErr == nil {
						if extra.Decision.Allow && !base.Decision.Allow {
							fail("P3 monotonicity: appending a deny turned a denial into an allow at %s", where)
						}
						if !base.Decision.Allow && !sameDecision(extra.Decision, base.Decision) {
							fail("P3 precedence: an earlier deny lost to an appended one at %s\n  base:  %+v\n  extra: %+v",
								where, base.Decision, extra.Decision)
						}
					}
				})
			}
			if failures > 5 {
				t.Errorf("%d further failures suppressed", failures-5)
			}
			t.Logf("%d requests, exhaustive over %d facts", requests, len(fam.Facts))
		})
	}
}
`)
	return b.String()
}

func quoteAll(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, fmt.Sprintf("%q", value))
	}
	return strings.Join(quoted, ", ")
}
