// Code generated by cervorules-vocabgen; DO NOT EDIT.

package vocab

import cervorules "github.com/cervantesh/cervo-rules/v3/core"

const (
	OperationDeploy        cervorules.Operation = "deploy"
	OperationMessageCreate cervorules.Operation = "message_create"
)

const (
	TargetDeployer      cervorules.Target = "deployer"
	TargetMessageWorker cervorules.Target = "message_worker"
)

const (
	ExecutorStandardExecutor cervorules.Executor = "standard_executor"
)

const (
	FactChangeFreeze   = "change_freeze"
	FactEnvironment    = "environment"
	FactErrorBudgetPct = "error_budget_pct"
	FactErrorRatePct   = "error_rate_pct"
	FactQueueDepth     = "queue_depth"
)

func Vocabulary() cervorules.Vocabulary {
	return cervorules.NewVocabulary(
		cervorules.AllowedOperations(
			OperationDeploy,
			OperationMessageCreate,
		),
		cervorules.AllowedTargets(
			TargetDeployer,
			TargetMessageWorker,
		),
		cervorules.AllowedExecutors(
			ExecutorStandardExecutor,
		),
	)
}
