package vocabgen

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"io"
	"regexp"
	"sort"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

const defaultImportPath = "github.com/cervantesh/cervo-rules/v3/core"

var packageNamePattern = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// Options controls v3 vocabulary code generation.
type Options struct {
	PackageName string
	ImportPath  string
	Reader      io.Reader
}

type spec struct {
	Operations map[string]specEntry `yaml:"operations" json:"operations"`
	Targets    map[string]specEntry `yaml:"targets" json:"targets"`
	Executors  map[string]specEntry `yaml:"executors" json:"executors"`
}

type specEntry struct {
	Description string `yaml:"description" json:"description"`
	GoName      string `yaml:"go_name" json:"go_name"`
}

// Generate reads a v3 vocabulary spec and returns formatted Go source.
func Generate(options Options) (string, error) {
	if err := validateOptions(options); err != nil {
		return "", err
	}
	parsed, err := parseSpec(options.Reader)
	if err != nil {
		return "", err
	}
	importPath := strings.TrimSpace(options.ImportPath)
	if importPath == "" {
		importPath = defaultImportPath
	}
	source, err := renderSource(options.PackageName, importPath, parsed)
	if err != nil {
		return "", err
	}
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return "", fmt.Errorf("format generated source: %w\n%s", err, source)
	}
	return string(formatted), nil
}

func validateOptions(options Options) error {
	if !packageNamePattern.MatchString(options.PackageName) {
		return fmt.Errorf("invalid package name %q", options.PackageName)
	}
	if options.Reader == nil {
		return errors.New("missing input reader")
	}
	return nil
}

func parseSpec(reader io.Reader) (spec, error) {
	var parsed spec
	decoder := yaml.NewDecoder(reader)
	decoder.KnownFields(true)
	if err := decoder.Decode(&parsed); err != nil {
		return spec{}, fmt.Errorf("decode vocabulary spec: %w", err)
	}
	if parsed.Operations == nil {
		parsed.Operations = map[string]specEntry{}
	}
	if parsed.Targets == nil {
		parsed.Targets = map[string]specEntry{}
	}
	if parsed.Executors == nil {
		parsed.Executors = map[string]specEntry{}
	}
	return parsed, nil
}

func renderSource(packageName string, importPath string, parsed spec) (string, error) {
	operations, err := buildConstants("Operation", "Operation", parsed.Operations)
	if err != nil {
		return "", err
	}
	targets, err := buildConstants("Target", "Target", parsed.Targets)
	if err != nil {
		return "", err
	}
	executors, err := buildConstants("Executor", "Executor", parsed.Executors)
	if err != nil {
		return "", err
	}

	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by cervorules-vocabgen; DO NOT EDIT.")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "package %s\n\n", packageName)
	fmt.Fprintf(&b, "import cervorules %q\n\n", importPath)
	writeConstBlock(&b, operations)
	writeConstBlock(&b, targets)
	writeConstBlock(&b, executors)
	writeVocabularyFunc(&b, operations, targets, executors)
	return b.String(), nil
}

type generatedConstant struct {
	Name  string
	Type  string
	Value string
}

func buildConstants(prefix string, typ string, values map[string]specEntry) ([]generatedConstant, error) {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	seen := map[string]string{}
	constants := make([]generatedConstant, 0, len(keys))
	for _, key := range keys {
		normalized := normalizeValue(key)
		if normalized == "" {
			return nil, fmt.Errorf("empty %s value", strings.ToLower(prefix))
		}
		name := prefix + entryName(values[key], normalized)
		if previous, ok := seen[name]; ok {
			return nil, fmt.Errorf("duplicate generated constant %s for %q and %q", name, previous, key)
		}
		seen[name] = key
		constants = append(constants, generatedConstant{Name: name, Type: typ, Value: normalized})
	}
	return constants, nil
}

func writeConstBlock(b *bytes.Buffer, constants []generatedConstant) {
	if len(constants) == 0 {
		return
	}
	fmt.Fprintln(b, "const (")
	for _, constant := range constants {
		fmt.Fprintf(b, "%s cervorules.%s = %q\n", constant.Name, constant.Type, constant.Value)
	}
	fmt.Fprintln(b, ")")
	fmt.Fprintln(b)
}

func writeVocabularyFunc(b *bytes.Buffer, operations []generatedConstant, targets []generatedConstant, executors []generatedConstant) {
	fmt.Fprintln(b, "func Vocabulary() cervorules.Vocabulary {")
	fmt.Fprintln(b, "return cervorules.NewVocabulary(")
	writeAllowedCall(b, "AllowedOperations", operations)
	writeAllowedCall(b, "AllowedTargets", targets)
	writeAllowedCall(b, "AllowedExecutors", executors)
	fmt.Fprintln(b, ")")
	fmt.Fprintln(b, "}")
}

func writeAllowedCall(b *bytes.Buffer, name string, constants []generatedConstant) {
	if len(constants) == 0 {
		return
	}
	fmt.Fprintf(b, "cervorules.%s(\n", name)
	for _, constant := range constants {
		fmt.Fprintf(b, "%s,\n", constant.Name)
	}
	fmt.Fprintln(b, "),")
}

func normalizeValue(value string) string {
	return strings.ToLower(strings.TrimSpace(value))
}

func entryName(entry specEntry, value string) string {
	if strings.TrimSpace(entry.GoName) != "" {
		return strings.TrimSpace(entry.GoName)
	}
	return exportName(value)
}

func exportName(value string) string {
	var b strings.Builder
	upperNext := true
	for _, r := range value {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			if upperNext {
				b.WriteRune(unicode.ToUpper(r))
				upperNext = false
				continue
			}
			b.WriteRune(r)
			continue
		}
		upperNext = true
	}
	return b.String()
}
